name: Run Lady Popular Bot

on:
  schedule:
    - cron: '0 */2 * * *'  # Every 2 hours
  workflow_dispatch:       # Allow manual runs too

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🤖 Run Lady Popular bot
        run: node burn-energy.js
        env:
          LP_EMAIL: ${{ secrets.LP_EMAIL }}
          LP_PASSWORD: ${{ secrets.LP_PASSWORD }}
